# Generated by Django 2.2.1 on 2019-05-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VFXWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='images/vfx')),
                ('video_link', models.URLField(null=True)),
                ('categorie', models.CharField(choices=[('comp', 'Compositing'), ('mat', 'Matte Painting'), ('gre', 'Green Screen'), ('oth', 'Others')], default='oth', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WebWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='images/web')),
                ('link', models.URLField(null=True)),
            ],
        ),
    ]
