# Generated by Django 2.2.1 on 2019-05-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacolley_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vfxwork',
            name='categorie',
        ),
        migrations.AddField(
            model_name='vfxwork',
            name='category',
            field=models.CharField(choices=[('comp', 'Compositing'), ('mat', 'Matte Painting'), ('trk', 'Tracking/Green Screen'), ('oth', 'Others')], default='oth', max_length=50),
        ),
    ]
